In [1]:
os.getcwd() 

'/Users/biancaziliotto/Desktop/GitRepo/MLx2'

In [2]:
os.chdir('src')

In [3]:
from MLP import MLP 

In [4]:
mlp = MLP([], 2, 1, "Sigm")


In [5]:
mlp.layers
mlp.input_size
mlp.output_size

1

In [6]:
import numpy as np
X = np.ndarray((4,2))
X[0, :]= [1, 2]
X[1, :]= [1, 4]
X[2, :]= [2, 5]
X[3, :]= [3, 6]
y_true  = np.ndarray((4,1))
y_true[:,0] = [3,5,7,9]

print(X)
print(y_true)
z = np.concatenate((X,y_true), axis = 1)
print(type(z))
np.random.shuffle(z)
prova= np.array_split(z, 2, axis = 1)
print(prova[0])


[[1. 2.]
 [1. 4.]
 [2. 5.]
 [3. 6.]]
[[3.]
 [5.]
 [7.]
 [9.]]
<class 'numpy.ndarray'>
[[1. 2.]
 [1. 4.]
 [2. 5.]
 [3. 6.]]


In [7]:
mlp.fit(X, y_true, n_epochs = 20, batch_size=1, initialization_str = "scaled", scale = 0.1, error_function_str= "MSE", optimizer_str = "gradient descent", regularization_function_str= "no")

[[ 9.46453362]
 [37.85813448]]
[[ -9.46453362]
 [-37.85813448]]
[[-0.]
 [-0.]]
[[0.]
 [0.]]
[[-0.]
 [-0.]]
[[0.]
 [0.]]
[[ -855.64418445]
 [-1852.00024445]]
[[ 855.64418445]
 [1852.00024445]]
Epoch 0: MSE = 102362101.82303149
[[ 9681.5136254]
 [19363.0272508]]
[[ -9681.5136254]
 [-19363.0272508]]
[[-0.]
 [-0.]]
[[0.]
 [0.]]
[[-0.]
 [-0.]]
[[0.]
 [0.]]
[[ -494082.57227447]
 [-1182441.76084165]]
[[ 494082.57227447]
 [1182441.76084165]]
Epoch 1: MSE = 40573275862085.36
[[5.19914549e+07]
 [1.03982910e+08]]
[[-5.19914549e+07]
 [-1.03982910e+08]]
[[-0.]
 [-0.]]
[[0.]
 [0.]]
[[-0.]
 [-0.]]
[[0.]
 [0.]]
[[-1.34837793e+09]
 [-3.75941592e+09]]
[[1.34837793e+09]
 [3.75941592e+09]]
Epoch 2: MSE = 3.908649590810365e+20
[[8.71407678e+10]
 [2.17851920e+11]]
[[-8.71407678e+10]
 [-2.17851920e+11]]
[[-0.]
 [-0.]]
[[0.]
 [0.]]
[[-0.]
 [-0.]]
[[0.]
 [0.]]
[[-4.19885347e+12]
 [-9.71142308e+12]]
[[4.19885347e+12]
 [9.71142308e+12]]
Epoch 3: MSE = 2.7524370357828794e+27
[[5.02996718e+13]
 [1.00599344e+14]]
[