In [1]:
import sys;print(sys.version)

3.10.8 (v3.10.8:aaaf517424, Oct 11 2022, 10:14:40) [Clang 13.0.0 (clang-1300.0.29.30)]


In [1]:
os.getcwd() 

'/Users/biancaziliotto/Desktop/GitRepo/MLx2'

In [2]:
os.chdir('src')

In [3]:
from MLP import MLP 

In [4]:
mlp = MLP(0, [], 3, 2)

In [5]:
mlp.layers

In [6]:
mlp = MLP(1, [1], 3, 2)

TypeError: Layer.__init__() takes 1 positional argument but 4 were given

In [18]:
import numpy as np
X = np.ndarray((4,3))
print(X)
mlp.predict(X)

[[1.49166815e-154 2.32035664e+077 1.49166815e-154]
 [3.11108962e+231 2.15592908e-314 2.15723167e-314]
 [2.15595346e-314 2.15595346e-314 1.49166815e-154]
 [2.68678943e+154 2.16920450e-314 8.34404887e-309]]


Exception: Dimension Error!

In [17]:
print(np.shape(mlp.layers[0]._biases)[0])

2
