In [1]:
import sys;print(sys.version)

3.10.8 (v3.10.8:aaaf517424, Oct 11 2022, 10:14:40) [Clang 13.0.0 (clang-1300.0.29.30)]


In [2]:
os.getcwd() 

'/Users/biancaziliotto/Desktop/GitRepo/MLx2'

In [1]:
os.chdir('src')

In [3]:
from MLP import MLP 

In [6]:
mlp = MLP(0, [], 3, 2)

In [7]:
mlp.layers

In [9]:
mlp = MLP(1, [1], 3, 2)

TypeError: Layer.__init__() takes 1 positional argument but 4 were given

In [8]:
import numpy as np
X = np.ndarray((4,3))
print(X)
mlp.predict(X)

[[ 1.49166815e-154 -4.33473565e-311  2.21557135e-314]
 [ 2.21559655e-314  2.21559661e-314  2.21559129e-314]
 [ 2.21551131e-314  2.21558513e-314  2.21558517e-314]
 [ 2.21559666e-314  2.21551782e-314  8.34404913e-309]]


AttributeError: 'Fully_Connected_Layer' object has no attribute 'forward_propagation'