In [1]:
import sys;print(sys.version)

3.10.8 (v3.10.8:aaaf517424, Oct 11 2022, 10:14:40) [Clang 13.0.0 (clang-1300.0.29.30)]


In [2]:
os.getcwd() 

'/Users/dre/Desktop/GitRepo/DreRnc/MLx2'

In [3]:
os.chdir('src')

In [4]:
from MLP import MLP 

In [5]:
mlp = MLP([4, 5, 9, 4, 7], 3, 2, "Sigm")


4
5
9
4
7
2


In [6]:
mlp.layers

In [7]:
print(range(1,5)[3])

4


In [8]:
import numpy as np
X = np.zeros((4,3))

X[0][0] =1
print(X)

[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
mlp.fit(X, X[:,1:], batch_size=2, initialization_str = "scaled", scale = 0.1, error_function_str= "MSE", optimizer_str = "gradient_descent", regularization_function_str= "L1", )


UnboundLocalError: local variable 'scale' referenced before assignment

In [3]:
from RegularizationFunctions import get_regularization_instance


In [5]:
L = get_regularization_instance("L1")

In [6]:
a = L.derivative(1)